"""one-to-money

Revision ID: 28f0fdc9dba6
Revises: 696fad8f1975
Create Date: 2025-08-10 15:37:30.310504

"""
from typing import Sequence, Union

from alembic import op # type: ignore
import sqlalchemy as sa # type: ignore
import sqlmodel # type: ignore



# revision identifiers, used by Alembic.
revision: str = '28f0fdc9dba6'
down_revision: Union[str, Sequence[str], None] = '696fad8f1975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
