"""add user

Revision ID: ae7896429438
Revises: 379e9802b701
Create Date: 2025-08-09 13:54:25.017685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # type: ignore



# revision identifiers, used by Alembic.
revision: str = 'ae7896429438'
down_revision: Union[str, Sequence[str], None] = '379e9802b701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.VARCHAR(), server_default='user', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
